server:
   port: 8002
   
# 定义当前服务名
spring:
   application:
      name: crindex
      
zuul:
   routes:
      # 路由名 == 服务名
      base: 
         url: /simple/163
         path: http://www.163.com
         
      index: 
         url: /index/**
         serviceId: crindex